# Generated by Django 4.1.7 on 2023-03-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_bill_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='curses',
            new_name='course',
        ),
    ]
