# Generated by Django 4.1.7 on 2023-03-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_rename_curses_bill_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
