"""
Django settings for CoursePj project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import paypalrestsdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fvzcpi*blyjd!-=u_e+5-9f&9=*hlqwrbq8r-dn(%5hed_=kbe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Courses.apps.CoursesConfig',
    'rest_framework',
    'captcha',
]


RECAPTCHA_PUBLIC_KEY = '6Ldu0BolAAAAAJ2xMnhcRgPnpHYStpQU86jDCu75'
RECAPTCHA_PRIVATE_KEY = '6Ldu0BolAAAAAA1B9dqF5z5BDef65nmJta_rk44c'
# SILENCED_SYSTEM_CHECKS = 'captcha.recaptcha_test_key_error'

SECURE_REFERRER_POLICY = 'same-origin'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Courses.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CoursePj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'coursesdb',
        'USER': 'root',

        'PASSWORD': 'Admin@123'


    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
RECAPTCHA_PUBLIC_KEY = '6LcnBx4lAAAAAOKQhGsBRG-ny3h1iyKW-JMbIgL0'
RECAPTCHA_PRIVATE_KEY = '6LcnBx4lAAAAAKCBjg7iC1oFu6gK-qhMRj0CoHmP'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


paypalrestsdk.configure({
  "mode": "sandbox", # sandbox hoặc live
  "client_id": "AeBefkwCv250k-_6xDSstx5dLPU8NcQouAc3j4Bel1ZhCqhsx9Ftrg9Bn9Y80UHyz5jeFCYm6PqvrUFX",
  "client_secret": "EPER87aLzApN3ZxtCjI93P59nLsrbrRiO8YW-IXaaYFDAF6S-O4iNJOtu15HZw0decUGEkve_8wiLC_D"
})

